name: AkatsukiRDP

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:
    - name: Загрузка Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/gamegame1236/dedic-top/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githubusercontent.com/gamegame1236/dedic-top/main/loop.bat -OutFile loop.bat
    - name: Загрузка программ.
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/gamegame1236/dedic-top/main/launcher/Node.js.lnk -OutFile Node.js.lnk
        Invoke-WebRequest https://raw.githubusercontent.com/gamegame1236/dedic-top/main/launcher/FastConfigVPS_v2.3.exe -OutFile "FastConfigVPS_v2.3.exe"
        Invoke-WebRequest https://raw.githubusercontent.com/gamegame1236/dedic-top/main/launcher/Visual%20Studio%202019.lnk -OutFile "Visual Studio 2019.lnk"
        Invoke-WebRequest https://download.radmin-vpn.com/download/files/Radmin_VPN_1.2.4457.1.exe -Outfile radmin.exe
        Invoke-WebRequest https://download.oracle.com/java/17/archive/jdk-17.0.4.1_windows-x64_bin.msi -Outfile java.msi
        Invoke-WebReuqest https://dl.google.com/drive-file-stream/GoogleDriveSetup.exe -Outfile drive.exe
    - name: Загрузка Ngrok файла.
      run: Expand-Archive ngrok.zip
    - name: Подключение к учётной записи Ngrok.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Включение доступа RDP.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy Node.js.lnk C:\Users\Public\Desktop\Node.js.lnk
        copy "FastConfigVPS_v2.3.exe" "C:\Users\Public\Desktop\FastConfigVPS_v2.3.exe"
        copy "Visual Studio 2019.lnk" "C:\Users\Public\Desktop\Visual Studio 2019.lnk"
        copy radmin.exe C:\Users\Public\Desktop\radmin.exe
        copy java.exe C:\Users\Public\Desktop\java.msi
        copy drive.exe C:\Users\Public\Desktop\drive.exe
    - name: Создание туннелей.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Подключение к CPU 2 - 7 ГБ оперативной памяти - 256 SSD.
      run: cmd /c start.bat
    - name: Сделано успешно! Вы можете закрыть вкладку.
      run: cmd /c loop.bat
